### ISSUE TITLE
Problems on Nuxt.js Frontend, Attestation Error on different API URL

### ISSUE THREAD

**Issue by ssgnoe** [Laragear/WebAuthn#44]
### PHP & Platform

8.1.20 - Cent OS (Plesk)

### Laravel version

9.0

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

No Error Message

### Description

Sorry, I'm not sure wether this is an issue, but searching for help.
I'm using Nuxt.js Frontend and Laravel Backend, authenticated with Laravel Sanctum Cookie Based.
Frontend URL: example.com Backend URL: api.example.com, so Cookie Based Auth works fine here, but not Webauthn I get the Error "**Attestation Error: Relying Party ID not scoped to current**"

On localhost:3000 for frontend and 8010 for backend everything is working fine. I think the problem comes from difference in URL, but I don't know how to configure, for not getting this error. Is this possible?
Thanks!

### Reproduction

```php
Install Frontend and Backend on different URLs
```

**Comment by DarkGhostHunter** [comment]
Yeah, I’m pretty sure because the port is part of the URL.I could make an option on development to not verify the the URL if the public key is mapped to localhost or “.localhost” or “.local”. You should be able to edit the attestation pipeline with a list of pipes without that check, in the meantime. Italo Baeza C.El 01-07-2023, a la(s) 04:45, ssgnoe ***@***.***> escribió:﻿
PHP & Platform
8.1.20 - Cent OS (Plesk)
Database
No response
Laravel version
9.0
Have you done this?

 I have checked my logs and I'm sure is a bug in this package.
 I can reproduce this bug in isolation (vanilla Laravel install)
 I can suggest a workaround as a Pull Request

Expectation
No Error Message
Description
Sorry, I'm not sure wether this is an issue, but searching for help.
I'm using Nuxt.js Frontend and Laravel Backend, authenticated with Laravel Sanctum Cookie Based.
Frontend URL: example.com Backend URL: api.example.com, so Cookie Based Auth works fine here, but not Webauthn I get the Error "Attestation Error: Relying Party ID not scoped to current"
On localhost:3000 for frontend and 8010 for backend everything is working fine. I think the problem comes from difference in URL, but I don't know how to configure, for not getting this error. Is this possible?
Thanks!
Reproduction
Install Frontend and Backend on different URLs

Stack trace & logs
No response

**Comment by ssgnoe** [comment]
Oh damn... I could solve the problem by myself. I configured APP_URL wrong in .env. It did point to the backend and not the frontend URL. So now it is working fine. Thank you!

**Comment by ssgnoe** [comment]
After some testing I ran into a problem with other Laravel Functions using the APP_URL .env. Is there a chance to pass a different .env Variable for Frontend?
